### PR TITLE
Upgrade to DJL 0.15.0

### PR DESCRIPTION
**Pull request by deki**
Would be great if someone could also release it to Maven Central. Thank you!

### CODE REVIEW

**Comment by deki** [comment]
I just noticed `djl-spring-boot-console-sample` fails with `ai.djl.repository.zoo.ModelNotFoundException: No matching model with specified Input/Output type found.` on my machine. 
It is working with 0.14.0. Can you please verify? Am I missing something?

**Comment by frankfliu** [comment]
Will take a look.

**Review by frankfliu — APPROVED** [review]

**Comment by frankfliu** [comment]
@deki 

You accidentally removed `djl-spring-boot-starter-mxnet-auto` dependency from the console app. I have fixed it.

**Comment by deki** [comment]
Ops. Thanks @frankfliu!

**Pull request merged**
